In [12]:
%load_ext autoreload
%autoreload 2

%pip install pandas

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

Requirement already satisfied: pandas in c:\Users\muhoz\Documents\finserve\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\muhoz\Documents\finserve\.venv\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\muhoz\Documents\finserve\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\muhoz\Documents\finserve\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\muhoz\Documents\finserve\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [13]:
%pip install re

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement re (from versions: none)
ERROR: No matching distribution found for re

In [14]:
import pandas as pd
import re
df = pd.read_csv('C:\\Users\\muhoz\\Documents\\finserve\\data\\raw\\applicants.csv') 

df.head(10)
 # Replace with your actual file path

,person_id,full_name,date_of_birth,email,phone,person_age,person_income,person_home_ownership,person_emp_length,source_system,created_at
0,P-100000,Allison Hill,1991-05-17,donaldgarcia@example.net,+1-219-560-0133,34,67020.12,RENT,8.8,CRM,2025-11-03 14:08:53.954934
1,P-100001,Jennifer Cole,2005-07-30,lisa02@example.net,(254)923-5116x15594,20,21672.54,MORTGAGE,5.5,CRM,2025-06-30 15:34:46.422589
2,P-100002,Jamie Arnold,1996-07-05,barbara10@example.net,441.731.6475,29,27745.41,OWN,8.5,WEBSITE,2025-02-23 21:24:38.736240
3,P-100003,Mia Sutton,1987-11-26,lynchgeorge@example.net,527.264.8350,38,45996.33,RENT,9.5,PARTNER_PORTAL,2026-01-04 22:48:49.890093
4,P-100004,Austin Gentry,1990-07-30,jason76@example.net,724.523.8849x696,35,54328.97,RENT,1.2,CRM,2026-05-19 15:19:57.147449
5,P-100005,Johnny Campos,1986-10-21,hernandezernest@example.net,(791)366-9784x80184,39,43154.45,OWN,4.3,CRM,2025-01-11 14:57:12.817932
6,P-100006,Aaron Bowen,1999-12-15,teresa28@example.org,+1-948-293-2528x8095,26,40741.76,RENT,3.3,PARTNER_PORTAL,2024-09-06 09:26:12.405712
7,P-100007,William Roman,1996-01-20,brianhumphrey@example.org,671-882-2782,29,59442.82,OTHER,6.5,CRM,2026-04-26 13:10:35.613769
8,P-100008,Nicole Vaughn,1990-04-14,raymond57@example.net,213.331.5098x393,35,144048.62,Mortgage,3.4,WEBSITE,2025-10-28 20:39:09.026986
9,P-100009,Austin Johnson,1998-05-04,chad34@example.net,838.729.9737x6311,27,28351.21,RENT,7.5,WEBSITE,2025-04-12 17:46:14.772899

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   person_id              1600 non-null   str
 1   full_name              1600 non-null   str
 2   date_of_birth          1600 non-null   str
 3   email                  1600 non-null   str
 4   phone                  1552 non-null   str
 5   person_age             1600 non-null   int64
 6   person_income          1600 non-null   float64
 7   person_home_ownership  1600 non-null   str
 8   person_emp_length      1600 non-null   float64
 9   source_system          1600 non-null   str
 10  created_at             1600 non-null   str
dtypes: float64(2), int64(1), str(8)
memory usage: 137.6 KB

In [16]:
df.isnull().sum()

person_id                 0
full_name                 0
date_of_birth             0
email                     0
phone                    48
person_age                0
person_income             0
person_home_ownership     0
person_emp_length         0
source_system             0
created_at                0
dtype: int64

In [17]:
def clean_phone(value):
    s = str(value).strip().lower()

    # Handle missing/junk values
    if s in ['nan', 'none', '', 'null', '-']:
        return None

    # Strip extension (x1234)
    s = re.split(r'x\d+', s)[0]

    # Keep only digits
    digits = re.sub(r'\D', '', s)

    # Normalize to +1XXXXXXXXXX
    if len(digits) == 11 and digits.startswith('1'):
        digits = digits[1:]
    elif len(digits) == 13 and digits.startswith('001'):
        digits = digits[3:]

    if len(digits) == 10:
        return '+1' + digits

    return None  # couldn't normalize -> leave as missing for now

In [18]:
# Apply and overwrite the column directly
df['phone'] = df['phone'].apply(clean_phone)

In [19]:
df['phone']

0       +12195600133
1       +12549235116
2       +14417316475
3       +15272648350
4       +17245238849
            ...
1595    +18064250230
1596    +13212560387
1597    +13373647476
1598    +17555868190
1599    +14506029573
Name: phone, Length: 1600, dtype: str

In [20]:
def clean_person_home_ownership(value):
  s = str(value).upper()

  return s

df['person_home_ownership'] = df['person_home_ownership'].apply(clean_person_home_ownership)

In [24]:
df['person_home_ownership'].head(40)

0         RENT
1     MORTGAGE
2          OWN
3         RENT
4         RENT
5          OWN
6         RENT
7        OTHER
8     MORTGAGE
9         RENT
10         OWN
11    MORTGAGE
12         OWN
13    MORTGAGE
14       OTHER
15    MORTGAGE
16        RENT
17        RENT
18       OTHER
19    MORTGAGE
20    MORTGAGE
21        RENT
22         OWN
23        RENT
24        RENT
25       OTHER
26    MORTGAGE
27    MORTGAGE
28    MORTGAGE
29        RENT
30         OWN
31         OWN
32       OTHER
33         OWN
34        RENT
35        RENT
36       OTHER
37         OWN
38    MORTGAGE
39       OTHER
Name: person_home_ownership, dtype: str

In [28]:
df.head(700)

,person_id,full_name,date_of_birth,email,phone,person_age,person_income,person_home_ownership,person_emp_length,source_system,created_at
0,P-100000,Allison Hill,1991-05-17,donaldgarcia@example.net,+12195600133,34,67020.12,RENT,8.8,CRM,2025-11-03 14:08:53.954934
1,P-100001,Jennifer Cole,2005-07-30,lisa02@example.net,+12549235116,20,21672.54,MORTGAGE,5.5,CRM,2025-06-30 15:34:46.422589
2,P-100002,Jamie Arnold,1996-07-05,barbara10@example.net,+14417316475,29,27745.41,OWN,8.5,WEBSITE,2025-02-23 21:24:38.736240
3,P-100003,Mia Sutton,1987-11-26,lynchgeorge@example.net,+15272648350,38,45996.33,RENT,9.5,PARTNER_PORTAL,2026-01-04 22:48:49.890093
4,P-100004,Austin Gentry,1990-07-30,jason76@example.net,+17245238849,35,54328.97,RENT,1.2,CRM,2026-05-19 15:19:57.147449
...,...,...,...,...,...,...,...,...,...,...,...
695,P-100695,Amy Cameron,1997-04-19,timothywilliams@example.org,+16289556608,28,46887.91,OTHER,9.5,WEBSITE,2024-07-06 12:03:42.591941
696,P-100696,Jennifer Jones,1977-02-12,brittanyclark@example.net,+16056195826,48,43947.01,OWN,12.3,WEBSITE,2025-07-14 16:23:31.599215
697,P-100697,Caitlin Harris,2005-01-27,matthew54@example.com,+14473079863,20,78055.05,OTHER,0.9,PARTNER_PORTAL,2024-07-19 05:08:22.861951
698,P-100698,Natalie Sawyer,1993-03-10,kathleenfitzgerald@example.com,+12396457039,32,26188.97,RENT,1.1,BRANCH,2024-06-28 16:33:58.729670
699,P-100699,Shannon Clark,1991-04-04,dcortez@example.com,+12272789431,34,76691.54,RENT,4.5,CRM,2026-02-10 11:01:59.703130

In [ ]:
df.to_csv("C:\\Users\\muhoz\\Documents\\finserve\\data\\processed\\applicants.csv", index=False)

OSError: Cannot save file into a non-existent directory: 'data\processed'